### ISSUE TITLE
Sync fails: Note with the same uid already exists

### ISSUE THREAD

**Issue by havogt** [dnote/cli#137]
Syncing worked for a while, now I get the following error message.

```
Server error: reducing actions: reducing action add_note: reducing an action: Note with the same uid already exists
```
How can I recover from that error?
What information should I provide to debug the problem?

**Comment by sungwoncho** [comment]
sounds like all your local changes were committed to the server, but the CLI is having trouble syncing form the server. In this case, recovering would be as simple as overeriding local copy of Dnote with the server data.

To confirm that your changes were committed, could you share the full output of `dnote sync` command?

```
▶ dnote s
  • writing changes (total 0). done.
  • resolving delta (total 0). done.
  ✔ success
```

we would like to see that "writing changes total" is 0. If so, it is safe to simply back up the current `~/.dnote` directory, and run `dnote login` and `dnote sync` again. A new `~/.dnote` will be created.

I am sorry for the inconvenience. I am working on a new sync mechanism based on timestamps rather than action log because action-based sync is proving to be buggy.

**Comment by sungwoncho** [comment]
Also what version are you using? Alternatively we can patch the CLI to ignore duplicate uuid.

**Comment by havogt** [comment]
Thanks for looking into the issue!
I have some non-synced changes locally. I could try to do a clean sync and recover them manually, but this problem already happened to me on 2 machines. It's important that this thing gets fixed, as for me the whole purpose of the sync is, that I don't have to take care that things get lost...

```
  • writing changes (total 7).
  ⨯ Server error: reducing actions: reducing action add_note: reducing an action: Note with the same uid already exists
```

The issue appeared with 0.4.4, now I am on 0.4.8.

**Comment by sungwoncho** [comment]
Sure, I will apply a patch in the meantime and update you.

**Comment by sungwoncho** [comment]
@havogt Now the server will gracefully ignore if client syncs a duplicate note. Could you try now? If you run into more errors, could you share the full output? I will keep an eye out on the system.

**Comment by havogt** [comment]
It works! Thank you very much for the quick fix!
