### ISSUE TITLE
Use SQLite

### ISSUE THREAD

**Issue by sungwoncho** [dnote/cli#84]
Currently all dnotes are in a single JSON file which gets read every time read/write happens. Using a relational database will:

* increase stability through transaction (sync functionality)
* remove awkwardness around migration
* improve read speed through index (benchmark needed)

cons:

* Maybe larger bundle size? (TODO: measure this)
* Ejecting is harder because users no longer can just grep JSON and go.
  * However we can develop a built-in way to dump SQLite data. And if we can dump data in a more meaningful way than a single JSON file, it might be beneficial for users.

@YiiKuoChong @michielboekhoff @FearNotDaniel how do you feel about it?

**Comment by ykcmaster** [comment]
I don't have much experience when it comes to programming but here are a few of my thoughts on this.

**My thoughts**

- A relational database can help improve load, search and write speed (since currently we read, add/write/append and write everything to a file which might not be good once the user have a lot of dnotes. I'm not really sure about the advantages of a relational database other than ones I stated above.
- We should keep the JSON interface so that users can choose between 2 preferred option but set a default based on which one is better (in this case SQLite).
- If we use SQLite, could we implement this on the server side too? Instead of syncing dnote JSON file, we sync the sqlite files, maybe even support other databases such as PostgreSQL.

** How I think we should do it **

- Implement an interface based on a SQLite interface (maybe this? https://github.com/mattn/go-sqlite3).
- Allow user to choose between 2 preferred data storage types but set the default to SQLite
- Allow user to import and export between the 2 data storage types (JSON <----> SQLite)

Well that is what I think about the feature. Sorry about replying 1 month late, GitHub didn't send me an email or notifications even though I was mentioned. By the way can you clarify a few things to me please.

1. Why does using SQLite increase stablity.
2. Why does it remove awkwardness around migration
3. Why is Ejecting harder? (What is ejecting?)

@michielboekhoff @sungwoncho @FearNotDaniel

**Comment by michielboekhoff** [comment]
@sungwoncho - I must have missed this notification, sorry about that!

I like the idea of using a standardized storage method. SQLite in particular is very flexible and fast. I do wonder how relational the data is - but I've not had a recent look at how the data model has evolved.

Another interesting point to discuss is how to then map this relational model to entities. Do you want to go full-on ORM? Or do you want to keep it at a low level and write your SQL manually? Which approach would benefit dnote most?

Keeping two data storages seems like it would complicate things, as it's not quite as easy as having an interface with two implementations.

**Comment by michielboekhoff** [comment]
@sungwoncho - thanks for your response. 

I do like the fact we can now go for a more "migration-styled" approach, where we ship & run migrations every time the data model changes. 

As for ejecting, I don't see why it would be difficult to serialise the SQLite database into a JSON format (with no compatibility or stability guarantees). I could open a PR if need be.

**Comment by sungwoncho** [comment]
> I don't see why it would be difficult to serialise the SQLite database into a JSON format

That's a good point. I'm thinking that we should provide an official way to serialize to JSON so that users are not locked into dnote. That could be a separate project to avoid putting too much stuff to the CLI. (could be a shell script, go or even python?)

First, I will take crack at sqlite support using https://github.com/mattn/go-sqlite3.

**Comment by michielboekhoff** [comment]
> That could be a separate project

I like that idea a lot, @sungwoncho. I've opened #113 to discuss the JSON schema / approach for the tool. Off the back of that, a new tool can be created. I'm available to contribute, or maybe even hack something together as an MVP.

> First, I will take crack at sqlite support using https://github.com/mattn/go-sqlite3.

Good luck!

**Comment by sungwoncho** [comment]
Implemented in [v0.4.5](https://github.com/dnote/cli/releases/tag/v0.4.5). Any old data will be migrated to SQLite on first run.

While migrating notes in my machine, I faced error because there were duplicated note uuids. I will investigate further and come up with a standalone program that can be run to automatically fix issues of this sorts (`dnote-doctor`?). It is very nice that through SQLite we will have some measure in place to prevent this sort of data integrity issues in the days to come.
